draw keymap and user_config_build

diff --git a/.github/workflows/draw_keymaps.yaml b/.github/workflows/draw_keymaps.yaml
--- a/.github/workflows/draw_keymaps.yaml
+++ b/.github/workflows/draw_keymaps.yaml
@@ -1,81 +1,72 @@
 # Reusable workflow for drawing and committing an automated keymap diagram
+# for ZMK config repos using https://github.com/caksoylar/keymap-drawer
 name: Draw ZMK keymaps
 on:
   workflow_call:
     inputs:
       keymap_patterns:
-        description: "Path specification for keymaps to be parsed"
-        default: "config/*.keymap"
-        required: false
+        description: 'Path specification for keymaps to be parsed'
         type: string
+        default: 'config/*.keymap'
       config_path:
-        description: "Path to the keymap-drawer configuration file, ignored if non-existent"
-        default: "keymap-drawer/config.yaml"
-        required: false
+        description: 'Path to the keymap-drawer configuration file, ignored if non-existent'
         type: string
+        default: 'keymap_drawer.config.yaml'
       west_config_path:
-        description: "Path to the folder containing west.yml, e.g. `config`. If specified, west will be initialized to fetch modules defined in west.yml"
-        default: ""
-        required: false
+        description: 'Path to the folder containing west.yml, e.g. `config`. Set to empty to skip fetching modules from west.yml'
         type: string
+        default: 'config'
       output_folder:
-        description: "Output folder for SVG and YAML files"
-        default: "keymap-drawer"
-        required: false
+        description: 'Output folder for SVG and YAML files'
         type: string
+        default: 'keymap-drawer'
       json_path:
-        description: "Path containing <keymap>.json physical layout description files, ignored if non-existent"
-        default: "config"
-        required: false
+        description: 'Path containing <keymap>.json physical layout description files, ignored if non-existent'
         type: string
+        default: 'config'
       parse_args:
         description: "Map of keyboard names to extra `keymap parse` args, e.g. `corne:'--layer-names Def Lwr Rse Fun'`"
-        default: "charybdis: '-b keymap-drawer/charybdis.yaml'"
-        required: false
         type: string
       draw_args:
         description: "Map of keyboard names to extra `keymap draw` args, e.g. `corne:'-k corne_rotated -l LAYOUT_split_3x5_3'`"
-        default: ""
-        required: false
+        type: string
+      extra_keymap_yaml:
+        description: "Map of keyboard names to extra keymap YAMLs to be passed to `keymap draw` after the parsed one, e.g. `corne:'keymap-drawer/extra_combos.yaml'`"
         type: string
       commit_message:
-        description: "Commit message for updated images. Ignored if `amend_commit` is `true`."
-        default: "keymap-drawer render"
-        required: false
+        description: 'Commit message for updated images. Ignored if `amend_commit` is `true`.'
         type: string
+        default: 'keymap-drawer render'
       amend_commit:
-        description: "Whether to amend the last commit instead of creating a new one. Make sure you understand the implications of rewriting the branch history if you use this option!"
-        default: true
-        required: false
+        description: 'Whether to amend the last commit instead of creating a new one. Make sure you understand the implications of rewriting the branch history if you use this option!'
         type: boolean
       install_branch:
-        description: "Install keymap-drawer from a git branch, use empty for pypi release (default)"
-        default: ""
-        required: false
+        description: 'Install keymap-drawer from a git branch, use empty to install from a pypi release obeying `install_version` (default)'
         type: string
       install_repo:
-        description: "Install keymap-drawer from a different git remote, primarily for testing changes using a keymap-drawer fork. Ignored if `install_branch` is unset/empty."
-        default: "https://github.com/caksoylar/keymap-drawer.git"
-        required: false
+        description: 'Install keymap-drawer from a different git remote, primarily for testing changes using a keymap-drawer fork. Ignored if `install_branch` is unset/empty.'
+        type: string
+        default: 'https://github.com/caksoylar/keymap-drawer.git'
+      install_version:
+        description: 'Install keymap-drawer from pypi using the specified version, use empty for latest pypi release (default)'
         type: string
       destination:
-        description: "Add the output files to a commit, as artifacts or both, values: `commit`, `artifact`, `both`"
-        default: "commit"
-        required: false
+        description: 'Add the output files to a commit, as artifacts or both, values: `commit`, `artifact`, `both`'
         type: string
+        default: 'commit'
       artifact_name:
-        description: "Name of the produced artifact containing SVG and YAML outputs. Ignored if `destination` is `commit`."
-        default: "keymap_layouts"
-        required: false
+        description: 'Name of the produced artifact containing SVG and YAML outputs. Ignored if `destination` is `commit`.'
         type: string
+        default: 'drawings'
       fail_on_error:
-        description: "Fail the action if an error occurs during parse/draw"
-        default: true
-        required: false
+        description: 'Fail the action if an error occurs during parse/draw'
+        type: boolean
+      debug_mode:
+        description: 'Enable debug mode'
         type: boolean
     outputs:
       drawings:
-        description: "Archive with keymap in YAML and drawing in SVG formats"
+        description: 'Archive with keymap in YAML and drawing in SVG formats'
         value: ${{ jobs.draw.outputs.drawings }}
 
 jobs:
@@ -97,141 +88,121 @@ jobs:
 
       - name: Install keymap-drawer (pypi)
         if: inputs.install_branch == ''
-        run: python3 -m pip install keymap-drawer
+        run: |
+          [ -n "${{ inputs.install_version }}" ] && version="==${{ inputs.install_version }}" || version=""
+          pipx install "keymap-drawer$version"
 
       - name: Install keymap-drawer (git)
         if: inputs.install_branch != ''
-        run: python3 -m pip install "git+${{ inputs.install_repo }}@${{ inputs.install_branch }}"
+        run: pipx install "git+${{ inputs.install_repo }}@${{ inputs.install_branch }}"
 
       - name: Install west
         if: inputs.west_config_path != ''
-        run: python3 -m pip install west
+        run: pipx install west
 
-      - name: Cache west modules
-        if: inputs.west_config_path != ''
-        uses: actions/cache@v4
-        continue-on-error: true
-        env:
-          cache_name: cache-zephyr-3.5.0-modules
-        with:
-          path: |
-            modules/
-            tools/
-            zephyr/
-            bootloader/
-            zmk/
-          key: ${{ runner.os }}-build-${{ env.cache_name }}-${{ hashFiles('**/west.yml', '**/build.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache_name }}-
-            ${{ runner.os }}-build-
-            ${{ runner.os }}-
-
-      - name: West Init
+      - name: Fetch west modules
         if: inputs.west_config_path != ''
         run: |
-          ls -Rhl $GITHUB_WORKSPACE
           west init -l ${{ inputs.west_config_path }}
-
-      - name: West Update
-        if: inputs.west_config_path != ''
-        run: west update
+          west config --local manifest.project-filter " -zmk,-zephyr"
+          west update --fetch-opt=--filter=tree:0
 
       - name: Draw keymaps
         id: draw
-        env:
-          KEYMAP_raw_binding_map: >
-            {
-              "&bootloader": "BOOT LDR",
-              "&mkp RCLK": "R CLK",
-              "&mkp LCLK": "L CLK",
-              "&mkp MCLK": "Mid CLK",
-              "&mkp MB4": "BACK",
-              "&mkp MB5": "FWD",
-              "&mmv MOVE_UP": "MOVE UP",
-              "&mmv MOVE_DOWN": "MOVE D",
-              "&mmv MOVE_LEFT": "MOVE L",
-              "&mmv MOVE_RIGHT": "MOVE R",
-              "&msc MOVE_UP": "WHEEL D",
-              "&msc MOVE_DOWN": "WHEEL U",
-              "&msc MOVE_LEFT": "WHEEL L",
-              "&msc MOVE_RIGHT": "WHEEL R",
-              "&h_split": "HSPLIT",
-              "&v_split": "VSPLIT",
-              "&caps_word": "CAPS WORD",
-              "&td_bore": "L_BASE L_EXTRA",
-              "&tdmt": "L1/BS LCLICK",
-              "&tdbt": "L2/ESC RCLICK",
-              "&td_layers": "L_BASE L_PHOTO L_GAME",
-              "&td_cursor": "SCRL SLOW",
-              "&td_home": "~/",
-              "&td_equals": "=",
-              "td_hyphen": "-",
-              "td_grave": "`",
-              "detach_session": "DETACH",
-              "create_or_attach": "NEW SESH",
-              "sync_panes": "SYNC PANES",
-              "next_pane": "NEXT PANE",
-              "show_sessions": "SHOW SESHS",
-              "sync_panes": "-",
-              "&shrug": "SHRUG",
-              "&lgtm": "LGTM",
-              "&gcm": "GIT COMMIT",
-              "&clip_hist": "CLIP HIST",
-              "&shit": "SHIT SUDO",
-              "&new_dir": "NEW DIR",
-              "&py_iter": "PYTHON LOOP",
-              "&js_iter": "JS LOOP",
-              "&studio_unlock": "ZMK Studio"
-            }
+        continue-on-error: ${{ !inputs.fail_on_error }}
         run: |
+          [ "${{ inputs.debug_mode }}" == "true" ] && set -x
+
           get_args() {
               local keyboard=$2
+              local output=()
+
               eval set -- "$1"
               for arg; do
                   local key=${arg%%:*}
                   local val=${arg#*:}
                   if [ "$key" = "$keyboard" ]; then
-                      echo "$val"
+                      output+=("$val")
                       break
                   fi
               done
+              echo "${output[@]}"
           }
 
-          declare -a DRAWINGS
+          check_for_layout_args() {
+              local args=("$@")
+
+              for val in "-j" "--qmk-info-json" "-k" "--qmk-keyboard" "-z" "--zmk-keyboard" "-d" "--dts-layout" "--ortho-layout" "-n" "--cols-thumbs-notation"; do
+                  for item in "${args[@]}"; do
+                      if [ "$val" = "$item" ]; then return 0; fi
+                  done
+              done
+
+              return 1
+          }
+
+          shopt -s nullglob extglob
+
+          artifacts=()
           error_occurred=0
           mkdir -p "${{ inputs.output_folder }}"
 
           config_path="${{ inputs.config_path }}"
           [ -e "$config_path" ] && config_arg=(-c "$config_path") || config_arg=()
-          echo "INFO: using config args: ${config_arg[@]}"
+          echo "INFO: using config args:" "${config_arg[@]}"
+
+          [ "${{ inputs.debug_mode }}" == "true" ] && debug_arg="-d" || debug_arg=""
+
           for keymap_file in ${{ inputs.keymap_patterns }}; do
               keyboard=$(basename -s .keymap "$keymap_file")
               echo "INFO: drawing for $keyboard"
 
-              parse_args=$(get_args "${{ inputs.parse_args }}" "$keyboard")
-              echo "INFO:   got extra parse args: $parse_args"
-              draw_args=$(get_args "${{ inputs.draw_args }}" "$keyboard")
-              echo "INFO:   got extra draw args: $draw_args"
+              IFS=" " read -r -a parse_args        <<< "$(get_args "${{ inputs.parse_args }}" "$keyboard")"
+              echo "INFO:   got extra parse args:"       "${parse_args[@]}"
+              IFS=" " read -r -a draw_args         <<< "$(get_args "${{ inputs.draw_args }}" "$keyboard")"
+              echo "INFO:   got extra draw args:"        "${draw_args[@]}"
+              IFS=" " read -r -a extra_keymap_yaml <<< "$(get_args "${{ inputs.extra_keymap_yaml }}" "$keyboard")"
+              echo "INFO:   got extra keymap YAML args:" "${extra_keymap_yaml[@]}"
 
               json_path="${{ inputs.json_path }}"
-              if [ -f "$json_path/${keyboard}.json" ]; then
+              if check_for_layout_args "${draw_args[@]}"; then
+                  echo "INFO:   found layout specifiers in draw args"
+              elif [ -n "$json_path" ] && [ -f "$json_path/${keyboard}.json" ]; then
                   echo "INFO:   found $json_path/${keyboard}.json";
-                  draw_args+=" -j $json_path/${keyboard}.json"
+                  draw_args+=(-j "$json_path/${keyboard}.json")
+              else
+                  dts_candidates=({,config/}boards/*/*/${keyboard}-layout{,s}.dtsi)
+                  if [ ${#dts_candidates[@]} -gt 0 ]; then
+                      echo "INFO:   found ${dts_candidates[0]}";
+                      draw_args+=(-d "${dts_candidates[0]}")
+                  fi
               fi
 
-              keymap "${config_arg[@]}" parse -z "$keymap_file" $parse_args >"${{ inputs.output_folder }}/$keyboard.yaml" \
-              && keymap "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" $draw_args >"${{ inputs.output_folder }}/$keyboard.svg" \
-              || {
-                  echo "ERROR: parsing or drawing failed for $keyboard!"
-                  error_occurred=1
-              }
-              DRAWINGS+=(\"${{ inputs.output_folder }}/$keyboard.yaml\" \"${{ inputs.output_folder }}/$keyboard.svg\")
-          done
-          IFS=','
-          echo "DRAWINGS=[${DRAWINGS[*]}]" >> $GITHUB_OUTPUT
-          unset IFS
+              tmp_yaml=$(mktemp)
+              tmp_svg=$(mktemp)
 
-          if [ "${{ inputs.fail_on_error }}" == "true" ] && [ $error_occurred -eq 1 ]; then
+              if keymap $debug_arg "${config_arg[@]}" parse -z "$keymap_file" "${parse_args[@]}" >"$tmp_yaml"; then
+                  mv "$tmp_yaml" "${{ inputs.output_folder }}/$keyboard.yaml"
+                  artifacts+=("${{ inputs.output_folder }}/$keyboard.yaml")
+              else
+                  echo "ERROR: parsing failed for $keyboard!"
+                  error_occurred=1
+                  continue
+              fi
+
+              if keymap $debug_arg "${config_arg[@]}" draw "${{ inputs.output_folder }}/$keyboard.yaml" "${extra_keymap_yaml[@]}" "${draw_args[@]}" >"$tmp_svg"; then
+                  mv "$tmp_svg" "${{ inputs.output_folder }}/$keyboard.svg"
+                  artifacts+=("${{ inputs.output_folder }}/$keyboard.svg")
+              else
+                  echo "ERROR: drawing failed for $keyboard!"
+                  error_occurred=1
+              fi
+          done
+
+          joined_artifacts=$(printf '"%s", ' "${artifacts[@]}")
+          printf 'artifacts=[%s]\n' "${joined_artifacts%, }" >> "$GITHUB_OUTPUT"
+
+          if [ $error_occurred -eq 1 ]; then
               exit 1
           fi
 
@@ -245,13 +216,13 @@ jobs:
         if: ( inputs.destination == 'commit' || inputs.destination == 'both' )
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
-          file_pattern: "${{ inputs.output_folder }}/*.svg ${{ inputs.output_folder }}/*.yaml"
+          file_pattern: '${{ inputs.output_folder }}/*.svg ${{ inputs.output_folder }}/*.yaml'
           # So the previous commit is amended instead of creating a new one when desired
           # See:
           # - https://github.com/stefanzweifel/git-auto-commit-action#using---amend-and---no-edit-as-commit-options
           # - https://github.com/stefanzweifel/git-auto-commit-action/issues/159#issuecomment-845347950
           # - https://github.com/actions/checkout
-          commit_message: "${{ (inputs.amend_commit == true && steps.last_commit_message.outputs.msg) || inputs.commit_message }}"
+          commit_message: '${{ (inputs.amend_commit == true && steps.last_commit_message.outputs.msg) || inputs.commit_message }}'
           commit_options: "${{ (inputs.amend_commit == true && '--amend --no-edit') || '' }}"
           push_options: "${{ (inputs.amend_commit == true && '--force-with-lease') || '' }}"
           skip_fetch: ${{ inputs.amend_commit == true }}
@@ -261,7 +232,15 @@ jobs:
         if: ( inputs.destination == 'artifact' || inputs.destination == 'both' )
         uses: actions/upload-artifact@v4
         with:
-          name: "${{ inputs.artifact_name }}"
+          name: '${{ inputs.artifact_name }}'
           path: |
-            ${{ join(fromJSON(steps.draw.outputs.DRAWINGS), '
+            ${{ join(fromJSON(steps.draw.outputs.artifacts), '
             ') }}
+
+      - name: Check job success
+        if: ${{ !inputs.fail_on_error }}
+        run: |
+          if [ "${{ steps.draw.outcome }}" == "failure" ]; then
+            echo "The draw step failed for some keymaps, please check the logs of that step above!"
+            exit 1
+          fi
